"""initial schema

Revision ID: b2f56eadabd3
Revises: 
Create Date: 2026-08-27 13:56:24.882353
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b2f56eadabd3'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # citext — логин регистронезависим: блокировку обходили сменой регистра.
    # pg_trgm — поиск по подстроке в именах и телефонах клиентов.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=120), nullable=True),
    sa.Column('tg_first_name', sa.String(length=255), nullable=True),
    sa.Column('tg_last_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('source_code', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('birth_city', sa.String(length=255), nullable=True),
    sa.Column('zodiac_sign', sa.String(length=20), nullable=True),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_clients_telegram_id'))
    )
    op.create_index('ix_clients_first_contact_at', 'clients', ['first_contact_at'], unique=False)
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=False)
    op.create_index('ix_clients_source_code', 'clients', ['source_code'], unique=False)
    op.create_table('daily_stats',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('deals_paid_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deals_paid_amount', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('new_clients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_conversations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('response_time_sum_sec', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('response_time_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', 'user_id', name='pk_daily_stats')
    )
    op.create_table('gateway_workers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), server_default='25', nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_workers'))
    )
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_email_created_at', 'login_attempts', ['email', 'created_at'], unique=False)
    op.create_table('payment_requisites',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_masked', sa.String(length=64), nullable=True),
    sa.Column('details_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_requisites'))
    )
    op.create_table('telegram_accounts',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('funnel_stage', sa.Enum('warmup', 'diagnostic', 'sales', name='funnel_stage'), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash_enc', sa.LargeBinary(), nullable=False),
    sa.Column('session_enc', sa.LargeBinary(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'error', 'disconnected', name='account_status'), server_default='pending', nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('history_synced_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_accounts')),
    sa.UniqueConstraint('phone', name=op.f('uq_telegram_accounts_phone'))
    )
    op.create_index('ix_telegram_accounts_active_lease', 'telegram_accounts', ['is_active', 'lease_until'], unique=False)
    op.create_index('ix_telegram_accounts_status', 'telegram_accounts', ['status'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('accepting_leads', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('avatar_color', sa.String(length=7), server_default='#7A6BE0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_token_hash', sa.String(length=255), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_invite_token_hash', 'users', ['invite_token_hash'], unique=False)
    op.create_index('ix_users_last_seen_at', 'users', ['last_seen_at'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('account_managers',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], name=op.f('fk_account_managers_account_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_account_managers_assigned_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_managers_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'user_id', name='pk_account_managers')
    )
    op.create_index('ix_account_managers_user_id', 'account_managers', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index('ix_auth_sessions_user_id_revoked_at', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('conversations',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('responsible_id', sa.BigInteger(), nullable=True),
    sa.Column('responsible_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_client_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_manager_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awaiting_reply_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_blocked_by_client', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], name=op.f('fk_conversations_account_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_conversations_client_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], name=op.f('fk_conversations_responsible_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('client_id', 'account_id', name='uq_conversations_client_account')
    )
    op.create_index('ix_conversations_account_last_message', 'conversations', ['account_id', sa.literal_column('last_message_at DESC')], unique=False)
    op.create_index('ix_conversations_awaiting', 'conversations', ['awaiting_reply_since'], unique=False, postgresql_where=sa.text('awaiting_reply_since IS NOT NULL'))
    op.create_index('ix_conversations_client_id', 'conversations', ['client_id'], unique=False)
    op.create_index('ix_conversations_responsible_last_message', 'conversations', ['responsible_id', sa.literal_column('last_message_at DESC')], unique=False)
    op.create_table('event_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_kind', sa.Enum('user', 'system', 'gateway', name='actor_kind'), server_default='user', nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_event_log_actor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    op.create_index('ix_event_log_actor_created', 'event_log', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_event_log_entity', 'event_log', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('notes',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_notes_client_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_client_id_created_at', 'notes', ['client_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('deal_paid', 'account_assigned', 'account_unassigned', 'account_error', name='notification_kind'), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read_at', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index('ix_search_history_user_created', 'search_history', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_settings_updated_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('templates',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_templates_owner_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index('ix_templates_owner_sort', 'templates', ['owner_id', 'sort_order'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('direction', sa.Enum('in', 'out', name='message_direction'), nullable=False),
    sa.Column('author_kind', sa.Enum('client', 'manager', 'userbot', 'system', name='author_kind'), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('text', 'photo', 'video', 'document', 'voice', 'service', name='message_kind'), server_default='text', nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'read', 'failed', name='message_status'), server_default='sent', nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('random_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_messages_author_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('random_id', name=op.f('uq_messages_random_id'))
    )
    op.create_index('ix_messages_author_created', 'messages', ['author_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_messages_text_fts', 'messages', [sa.literal_column("to_tsvector('russian', coalesce(text, ''))")], unique=False, postgresql_using='gin')
    op.create_index('uq_messages_conversation_tg_id', 'messages', ['conversation_id', 'tg_message_id'], unique=True, postgresql_where=sa.text('tg_message_id IS NOT NULL'))
    op.create_table('attachments',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_attachments_client_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_attachments_conversation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index('ix_attachments_client_created', 'attachments', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_attachments_message_id', 'attachments', ['message_id'], unique=False)
    op.create_table('deals',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('sold_by_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.Enum('link', 'requisites', name='payment_method'), nullable=False),
    sa.Column('requisite_id', sa.BigInteger(), nullable=True),
    sa.Column('requisites_snapshot', sa.Text(), nullable=True),
    sa.Column('payment_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('draft', 'awaiting', 'paid', 'cancelled', 'expired', name='deal_status'), server_default='draft', nullable=False),
    sa.Column('total_amount', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('payment_url', sa.String(length=500), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_source', sa.Enum('manual', 'provider', name='paid_source'), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('edit_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_deals_client_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_deals_conversation_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_deals_created_by_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], name=op.f('fk_deals_paid_by_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisite_id'], ['payment_requisites.id'], name=op.f('fk_deals_requisite_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sent_message_id'], ['messages.id'], name=op.f('fk_deals_sent_message_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sold_by_id'], ['users.id'], name=op.f('fk_deals_sold_by_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index('ix_deals_client_created', 'deals', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_deals_conversation_status', 'deals', ['conversation_id', 'status'], unique=False)
    op.create_index('ix_deals_payment_code', 'deals', ['payment_code'], unique=False)
    op.create_index('ix_deals_sold_by_paid', 'deals', ['sold_by_id', 'paid_at'], unique=False)
    op.create_index('ix_deals_status_expires', 'deals', ['status', 'expires_at'], unique=False)
    op.create_table('outbox',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sending', 'done', 'failed', name='outbox_status'), server_default='pending', nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], name=op.f('fk_outbox_account_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_outbox_conversation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_outbox_message_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('message_id', name=op.f('uq_outbox_message_id'))
    )
    op.create_index('ix_outbox_account_status_next', 'outbox', ['account_id', 'status', 'next_attempt_at'], unique=False)
    op.create_index('ix_outbox_conversation_id', 'outbox', ['conversation_id'], unique=False)
    op.create_table('deal_events',
    sa.Column('deal_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('created', 'sent', 'edited', 'cancelled', 'expired', 'paid', 'reminded', name='deal_event_kind'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_deal_events_actor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_events_deal_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_events'))
    )
    op.create_index('ix_deal_events_deal_created', 'deal_events', ['deal_id', 'created_at'], unique=False)
    op.create_table('deal_items',
    sa.Column('deal_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_items_deal_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_items'))
    )
    op.create_index('ix_deal_items_deal_id', 'deal_items', ['deal_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('deal_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_payment_events_deal_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_payment_events_provider_event_id'))
    )
    op.create_index('ix_payment_events_deal_id', 'payment_events', ['deal_id'], unique=False)
    # ### end Alembic commands ###


    # --- ручные доводки поверх автогенерации ---

    op.execute("ALTER TABLE users ALTER COLUMN email TYPE citext")

    # Номера, видимые пользователю, стартуют с «красивых» значений:
    # клиент 84271, сделка DEAL-1042 — как на макетах.
    op.execute("ALTER SEQUENCE clients_id_seq RESTART WITH 80000")
    op.execute("ALTER SEQUENCE deals_id_seq RESTART WITH 1000")

    # Поиск по подстроке имени и телефона клиента
    op.execute(
        "CREATE INDEX ix_clients_display_name_trgm ON clients "
        "USING gin (coalesce(display_name, '') gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_clients_phone_trgm ON clients "
        "USING gin (coalesce(phone, '') gin_trgm_ops)"
    )

    # Значения настроек по умолчанию
    import json

    from app.models.misc import DEFAULT_SETTINGS

    for key, value in DEFAULT_SETTINGS.items():
        op.execute(
            sa.text(
                "INSERT INTO settings (key, value) VALUES (:k, cast(:v as jsonb)) "
                "ON CONFLICT (key) DO NOTHING"
            ).bindparams(k=key, v=json.dumps(value))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_events_deal_id', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('ix_deal_items_deal_id', table_name='deal_items')
    op.drop_table('deal_items')
    op.drop_index('ix_deal_events_deal_created', table_name='deal_events')
    op.drop_table('deal_events')
    op.drop_index('ix_outbox_conversation_id', table_name='outbox')
    op.drop_index('ix_outbox_account_status_next', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_deals_status_expires', table_name='deals')
    op.drop_index('ix_deals_sold_by_paid', table_name='deals')
    op.drop_index('ix_deals_payment_code', table_name='deals')
    op.drop_index('ix_deals_conversation_status', table_name='deals')
    op.drop_index('ix_deals_client_created', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_attachments_message_id', table_name='attachments')
    op.drop_index('ix_attachments_client_created', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('uq_messages_conversation_tg_id', table_name='messages', postgresql_where=sa.text('tg_message_id IS NOT NULL'))
    op.drop_index('ix_messages_text_fts', table_name='messages', postgresql_using='gin')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index('ix_messages_author_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_templates_owner_sort', table_name='templates')
    op.drop_table('templates')
    op.drop_table('settings')
    op.drop_index('ix_search_history_user_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notes_client_id_created_at', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_event_log_entity', table_name='event_log')
    op.drop_index('ix_event_log_actor_created', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index('ix_conversations_responsible_last_message', table_name='conversations')
    op.drop_index('ix_conversations_client_id', table_name='conversations')
    op.drop_index('ix_conversations_awaiting', table_name='conversations', postgresql_where=sa.text('awaiting_reply_since IS NOT NULL'))
    op.drop_index('ix_conversations_account_last_message', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_auth_sessions_user_id_revoked_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_account_managers_user_id', table_name='account_managers')
    op.drop_table('account_managers')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index('ix_users_last_seen_at', table_name='users')
    op.drop_index('ix_users_invite_token_hash', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_telegram_accounts_status', table_name='telegram_accounts')
    op.drop_index('ix_telegram_accounts_active_lease', table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_table('payment_requisites')
    op.drop_index('ix_login_attempts_email_created_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('gateway_workers')
    op.drop_table('daily_stats')
    op.drop_index('ix_clients_source_code', table_name='clients')
    op.drop_index('ix_clients_phone', table_name='clients')
    op.drop_index('ix_clients_first_contact_at', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
